### ISSUE TITLE
Aligning Consecutive Cuts

### ISSUE THREAD

**Issue by kmccleary-sharpe** [smujiang/Re-stained_WSIs_Registration#1]
Hello, 
I have found your code while researching the best way to align re-stained WSIs and how to align hematoxylin WSIs from adjacent tissue cuts. 

In my workflow, I have four adjacent tissue cuts with hematoxylin staining, and typical registration pipelines fail to align them, as the features from cut to cut vary more than the typical differences seen in re-stained slides. 

Do you have any thoughts on how to implement or adapt this pipeline to align adjacent tissue cuts?

Thank you for any help or tips that you can provide!

**Comment by smujiang** [comment]
Thanks for following up my work.
Generally, this tool is designed for aligning stain-and-restained WSIs. As I mentioned in the paper, the main limitation of this method is there should be no tissue rotation between two WSIs.  For the stain-and-restained WSIs,  the tissues are the same, and way of scanner mounting the slides determined there should be no rotation. 

However, for successive tissue cuts, there must be rotations between two slides when the tissues were placed on glass. So this method doesn't match your scenario.

If you don't have to use automatic method to align WSIs in your case, I recommond you to use some annotation tools (i.e. QuPath) to get the affine matrix. You need to find at least two pairs of cells in the two WSIs, and export your two annotated points out, so that you can calculate the affine transformation.
