### ISSUE TITLE
Dataset of WSIs

### ISSUE THREAD

**Issue by jiajundeng** [smujiang/Re-stained_WSIs_Registration#2]
Hi,
thanks for sharing your extraordinary work. I was inspired a lot by your nice work.  I am a student at TU Darmstadt in Germany and currently working on whole slide image registration as my master project. But I only have a very limited amount of raw WSI  for registration which is obviously not enough for optimizing and validating my algorithm. I would like to ask is it possible to share your dataset with me, not necessarily all of them? It would be nice that you can share it with me via google drive or any other online cloud which you are more comfortable with. I can pay for the costs incurred in the process, if necessary.  I know that my request is a bit abrupt and rude, but I don't want to give up any possibility that you might agree to it. Anyway, I wish you all the best sincerely. Thanks in advance! 
Best,
JJ

**Comment by smujiang** [comment]
Hi JJ,

Thanks for asking.
I’m regret to inform you that I’m not able to share the whole slide images with you due to Mayo Clinic patient data privacy policy. There are patient IDs in the original WSIs (with .svs extension). Unfortunately, those files are read-only files, I’m not able to anonymize those files for sharing. As all the computers connect to Mayo Clinic intranet are monitored by Mayo IT, I’m not going to send you that dataset. You may need to find other data source for developing.

Good luck.

Jun
