### ISSUE TITLE
Is it possible to register modified images after getting the offset

### ISSUE THREAD

**Issue by kaizen89** [smujiang/Re-stained_WSIs_Registration#3]
Hi,
Is it possible to register modified images after getting the offset? If so, how to proceed once I run the example code you provide?
Thank you

**Comment by smujiang** [comment]
Do you mean write the registered image to file? Actually, most whole slide images formats are read-only, it requires specific libraries to support file writing. In my opinion, if you focus on downstream analysis, rather than tackling writing whole slide image file, you can just do [pairwise patch extraction](https://github.com/smujiang/WSITools/blob/master/docs/patch_extraction/pairwise_patch_extraction.md), since you have to process image patches rather than entire whole slide image. 
Please note that the pairwise patch extraction in my repo does not take rotation into consideration either.
